function [visualSettings,outputString] = visualsettings(fps,xCells,yCells)

%       outputFolder: folder where the resulting video should be saved
%       gridCellSize: inflate cells to pixels
%       isobarWidth: width of the isobars (areas with similar distance)
%       drawVelocity: bool, display velocity field
%       distanceRefreshInterval: integer, distance field is reinitialized 
%           after n frames


outputString = ['singleblock', ' ', ...
    int2str(xCells + 1), 'x', ...
    int2str(yCells + 1), ...
    ' ', int2str(fps), 'fps'];

visualSettings = struct (...
    'fps', fps, ...
    'outputFolder', ['output\', outputString], ...
    'outputFile', [outputString '.avi'], ...
    'gridCellSize', 800 / xCells, ...
    'isobarWidth', 400 / xCells, ...
    'drawVelocity', false, ...
    'drawPressure', false, ...
    'distanceRefreshInterval', 1 ...
);

% clear old output
delete([visualSettings.outputFolder '\image*.png']);